# Site Settings
title: traversing time and space
email: rsdevonport1993@gmail.com
description: >
  A personal portfolio
baseurl: ""
<<<<<<< HEAD
url: "https://dastardlymut.github.io/"
=======
url: "https://dastardlymut.github.io"
>>>>>>> 9ead51f0dca3639a063c50c0e45cdb25be5f16e2
github_username:  dastardlymut
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
