theme: jekyll-theme-tactile

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : DastardlyMut's Blog
author :
  name : Sean Devonport
  email : rsdevonport1993@gmail.com
  github : dastardlymut
