theme: jekyll-theme-tactile

# Site Settings
title: traversing time and space
email: rsdevonport1993@gmail.com
description: >
  A personal portfolio.
baseurl: "/home/"
url: "http://localhost:4000/"
github_username:  dastardlymut
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM