# Site Settings
title: traversing time and space
email: elastic.tonetastic@gmail.com
description: >
  A personal portfolio
baseurl: ""
url: "https://tonetechnician.github.io/"
github_username:  tonetechnician
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
